### ISSUE TITLE
无法找到底层接口函数

### ISSUE THREAD

**Issue by WZTENG** [nihui/ncnn-android-mobilenetssd#2]
按说明一步步做了，编译时都是类似这样的：
pipeline.cpp:function ncnn::Pipeline::destroy(): error: undefined reference to 'vkDestroyPipeline'
.....
xxxxxxx.cpp:function ncnn::Pipeline::xxxxxxxx(): error: undefined reference to 'xxxxxxxxxx'
如何解决呢？
![image](https://user-images.githubusercontent.com/19603468/86305391-15eef000-bc44-11ea-8327-d33a8d06755d.png)

**Comment by nihui** [comment]
你是用这个cmake编译的？
https://github.com/nihui/ncnn-android-mobilenetssd/blob/master/app/src/main/jni/CMakeLists.txt

**Comment by WZTENG** [comment]
> 你是用这个cmake编译的？
> https://github.com/nihui/ncnn-android-mobilenetssd/blob/master/app/src/main/jni/CMakeLists.txt

clone 工程后，下载最新的 ncnn-android-vulkan-lib.zip 文件复制到 jni 文件夹，除了修改工程 SDK，NDK，Gradle 的版本外没动其它代码

**Comment by WZTENG** [comment]
android studio 4.0
ndk:21.3.6528147
sdk:29
gradle:6.1.1
buildToolsVersion "29.0.3"
cmake:3.10.2

**Comment by WZTENG** [comment]
解决了，必须安卓7.0及以上的手机。
